### ISSUE TITLE
About the release of the code

### ISSUE THREAD

**Issue by showgood163** [xh-liu/Open-Edit#1]
Hi there!

I'm interested in your work and I want to know when you plan to release the code. Will you also provide pretrained models for faster evaluation?

Thanks!

**Comment by xh-liu** [comment]
Thanks for your interest! I will release the code in two weeks.

**Comment by ghost** [comment]
@xh-liu the pretrained models need email access, can you please make them open via shared link thanks

**Comment by showgood163** [comment]
Hi!

There are bad files in the provided google cloud folder, namely vgg_19.pth and conceptual_vocab.pkl.
