### ISSUE TITLE
Some problems about training

### ISSUE THREAD

**Issue by VicZlq** [xh-liu/Open-Edit#2]
Hello, I'm very glad to see your open code. When I was reproducing, there were some problems
When training, prompt the lack of documents
FileNotFoundError: [Errno 2] No such file or directory: './datasets/conceptual/val_index.json'
Can you provide the file directory structure of your project? Thank you！

**Comment by xh-liu** [comment]
Hi, the dataset I used is downloaded from [https://ai.google.com/research/ConceptualCaptions/download](https://ai.google.com/research/ConceptualCaptions/download). val_index.json and train_index.json save the information of the paths and filenames of the images in training and validation splits.
