### ISSUE TITLE
AttributeError: 'OpenEditTrainer' object has no attribute 'get_latest_generated'

### ISSUE THREAD

**Issue by vithurshann** [xh-liu/Open-Edit#3]
Hi,

I am trying to train the image decoder on the Vizwiz dataset using bash train.sh and I get the following error and unsure how to fix it:
<img width="1192" alt="Screenshot 2020-12-17 at 19 16 36" src="https://user-images.githubusercontent.com/65983246/102532858-837cc480-409c-11eb-9ad8-10bd3fcbaf6e.png">

Thanks.

**Comment by xh-liu** [comment]
Sorry, it was because of a mistake while cleaning the code. I have fixed it and it should work now.
